[package]
name = "bilk"
version = "0.0.2"
edition = "2021"
authors = ["Collin Richards"]
description = "Miscellaneous convenience functions and traits"
repository = "https://github.com/richardscollin/bilk"
rust-version = "1.79"
license = "MIT OR Apache-2.0"
